import {
  McpAuthType,
  McpServerCapability,
  McpServerConfig,
} from '../interfaces';

export const PREDEFINED_MCP_SERVERS: McpServerConfig[] = [
  {
    slug: 'fhir',
    name: 'FHIR',
    description:
      'Connect to FHIR Server to manage patient records, observations, and more.',
    serverUrl: 'https://aae8e7f44e8c.ngrok-free.app/mcp/',
    serverUrlEnvVar: 'MCP_FHIR_SERVER_URL',
    iconUrl: 'https://hapi.fhir.org/baseR4/swagger-ui/raccoon.png',
    authType: McpAuthType.MCP_OAUTH,
    mcpOAuth: {
      scopes: [
        'user/DocumentReference.read',
        'patient/DiagnosticReport.read',
        'user/DiagnosticReport.read',
        'user/Media.read',
        'patient/AllergyIntolerance.read',
        'patient/Patient.read',
        'patient/Immunization.read',
        'user/MedicationDispense.read',
        'patient/CareTeam.read',
        'user/Patient.read',
        'user/Procedure.read',
        'user/Organization.read',
        'user/Device.read',
        'user/Binary.read',
        'patient/Device.read',
        'user/QuestionnaireResponse.read',
        'patient/MedicationAdministration.read',
        'patient/Medication.read',
        'user/Coverage.read',
        'patient/MedicationDispense.read',
        'patient/Encounter.read',
        'user/Location.read',
        'user/Practitioner.read',
        'patient/Binary.read',
        'user/Medication.read',
        'patient/Condition.read',
        'patient/MedicationRequest.read',
        'patient/Media.read',
        'patient/ServiceRequest.read',
        'user/PractitionerRole.read',
        'patient/Location.read',
        'user/CareTeam.read',
        'patient/DocumentReference.read',
        'patient/QuestionnaireResponse.read',
        'patient/Coverage.read',
        'user/AllergyIntolerance.read',
        'patient/Organization.read',
        'user/RelatedPerson.read',
        'user/Immunization.read',
        'patient/Goal.read',
        'patient/Practitioner.read',
        'user/Condition.read',
        'user/Encounter.read',
        'patient/Provenance.read',
        'patient/Specimen.read',
        'user/MedicationRequest.read',
        'patient/PractitionerRole.read',
        'patient/Procedure.read',
        'user/Provenance.read',
        'user/Observation.read',
        'user/Specimen.read',
        'user/MedicationAdministration.read',
        'user/CarePlan.read',
        'patient/CarePlan.read',
        'user/ServiceRequest.read',
        'patient/Observation.read',
        'patient/RelatedPerson.read',
        'user/Goal.read',
      ],
    },
    capabilities: [McpServerCapability.TOOLS, McpServerCapability.RESOURCES],
  },
  {
    slug: 'github',
    name: 'GitHub',
    description:
      'Connect to GitHub to manage repositories, issues, pull requests, and more.',
    serverUrl: 'https://api.githubcopilot.com/mcp',
    serverUrlEnvVar: 'MCP_GITHUB_SERVER_URL',
    iconUrl: 'https://github.githubassets.com/favicons/favicon.svg',
    authType: McpAuthType.OAUTH,
    oauth: {
      clientIdEnvVar: 'MCP_GITHUB_CLIENT_ID',
      clientSecretEnvVar: 'MCP_GITHUB_CLIENT_SECRET',
      authorizationUrl: 'https://github.com/login/oauth/authorize',
      tokenUrl: 'https://github.com/login/oauth/access_token',
      scopes: ['repo', 'read:user', 'user:email'],
    },
    capabilities: [McpServerCapability.TOOLS, McpServerCapability.RESOURCES],
  },
  {
    slug: 'linear',
    name: 'Linear',
    description:
      'Connect to Linear for issue tracking, project management, and team collaboration.',
    serverUrl: 'https://mcp.linear.app',
    serverUrlEnvVar: 'MCP_LINEAR_SERVER_URL',
    iconUrl: 'https://linear.app/favicon.ico',
    authType: McpAuthType.OAUTH,
    oauth: {
      clientIdEnvVar: 'MCP_LINEAR_CLIENT_ID',
      clientSecretEnvVar: 'MCP_LINEAR_CLIENT_SECRET',
      authorizationUrl: 'https://linear.app/oauth/authorize',
      tokenUrl: 'https://api.linear.app/oauth/token',
      scopes: ['read', 'write', 'issues:create', 'comments:create'],
    },
    capabilities: [McpServerCapability.TOOLS, McpServerCapability.RESOURCES],
  },
];

export const MCP_OAUTH_STATE_PREFIX = 'mcp_oauth_state_';
export const MCP_OAUTH_STATE_TTL_MS = 10 * 60 * 1000;
